name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@main
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: "openradar"
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          PUBLIC_REGISTRY_CHECK: true
          APPENDIX_FILE: "binder/appendix.txt"
  build:
    if: ${{ github.repository_owner == 'openradar' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: ams-open-radar-2023-dev

  link-check:
    if: ${{ github.repository_owner == 'openradar' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
