name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-book-pullrequest.yaml
    with:
      environment_name: ams-open-radar-2023-dev
      environment_file: environment.yml
      use_cached_environment: 'false'

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
