name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: ams-open-radar-2023-dev
      use_cached_environment: 'false'
      artifact_name: book-zip-${{ github.event.number }}