name: trigger-book-build
on:
  pull_request:

jobs:
  get-code:
    uses: ProjectPythia/cookbook-actions/.github/workflows/get-code.yaml@main
    with:
      code_artifact_name: code-zip-${{ github.event.number }}
